# config.py
BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
API_ID = "YOUR_API_ID"
API_HASH = "YOUR_API_HASH"
ALLOWED_GROUP_ID = "YOUR_ALLOWED_GROUP_ID"
FORCE_SUB_CHANNEL = "YOUR_FORCE_SUB_CHANNEL_USERNAME" # Must be like @username
ADMINS = ["ADMIN_USER_ID_1", "ADMIN_USER_ID_2"]
SPOTIPY_CLIENT_ID = "YOUR_SPOTIPY_CLIENT_ID"
SPOTIPY_CLIENT_SECRET = "YOUR_SPOTIPY_CLIENT_SECRET"
BOT_USERNAME = "YOUR_BOT_USERNAME" # Without @

# Upload mode: 'direct' or 'info'
UPLOAD_MODE = "direct"

# Queue system: True or False
QUEUE_ENABLED = False