version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_music_bot
    environment:
      # Database connection (connects to the postgres container)
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/music_bot_db"
      
      # REQUIRED: Bot configuration (YOU MUST SET THESE!)
      BOT_TOKEN: "${BOT
