# render.yaml
# This file configures the services for deploying the Telegram bot on Render.
# It defines a MongoDB database and a worker service to run the bot.

databases:
  # 1. MongoDB Database
  # This service creates a managed MongoDB database for the bot.
  - name: music-bot-db
    # The 'plan' can be 'free' for testing or a paid plan for production.
    plan: free
    databaseName: music_bot

services:
  # 2. Telegram Bot Service
  # This service runs the bot as a background worker using the existing Dockerfile.
  - type: worker
    name: telegram-music-bot
    # The 'plan' can be 'free' for testing or a paid plan for production.
    plan: free
    # Tells Render to use the Dockerfile in the root of the repository.
    dockerfilePath: ./Dockerfile
    # The command to start the bot.
    startCommand: python bot.py
    # Sets up the environment variables for the bot.
    envVars:
      # The MONGODB_URI is automatically created by Render and injected
      # from the database service defined above.
      - key: MONGODB_URI
        fromService:
          type: db
          name: music-bot-db
          property: connectionString
      # --- Secrets ---
      # These are sensitive values that you must set in the Render dashboard.
      # Create an "Environment Group" in Render and add these keys.
      - key: BOT_TOKEN
        sync: false # Set this in the Render dashboard
      - key: ADMINS
        sync: false # Set this in the Render dashboard (e.g., "12345,67890")
      - key: ALLOWED_GROUP_ID
        sync: false # Set this in the Render dashboard
      - key: BOT_USERNAME
        sync: false # Set this in the Render dashboard (e.g., "MyMusicBot")
      # --- Optional Secrets ---
      # Set these if you use the corresponding features.
      - key: FORCE_SUB_CHANNEL
        sync: false # Optional: Set this in the Render dashboard (e.g., "@mychannel")
      - key: SPOTIPY_CLIENT_ID
        sync: false # Optional: Set this for Spotify integration
      - key: SPOTIPY_CLIENT_SECRET
        sync: false # Optional: Set this for Spotify integration